config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :products do
    resources :auctions, only: [ :create ] do 
      resources :bids, only: [ :create ]
    end
    member do 
      put :transfer
    end
  end

  root 'products#index'

end

app/models/auction.rb
class Auction < ActiveRecord::Base
  belongs_to :product
  # bids implemented in the auction
  has_many :bids

  def top_bid
    bids.order(value: :desc).first
  end

  def current_bid
    top_bid.nil? ? value : top_bid.value
  end

  def ended?
    ends_at < Time.now
  end
end

app/models/bid.rb
class Bid < ActiveRecord::Base
  belongs_to :user
  belongs_to :auction

  # make sure the number entered is a number
  validates_numericality_of :value
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :user
  # now product has access to auctions
  has_one :auction

  def has_auction?
    # because of has_one :auction, we can now call on auction
    # go to the relationship, fetch the auction and see if it exists
    auction.present?
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :products
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/auctions_controller.rb
class AuctionsController <  ApplicationController
  def create
    product = Product.find params[:product_id]
    # use merge to join product id into the auction_params hash
    auction = Auction.new auction_params.merge! product_id: product.id

    if auction.save
      redirect_to product, notice: "Product was put to auction."
    else
      redirect_to product, alert: "Something went wrong, please review your data."
    end
  end

  def auction_params
    params.require(:auction).permit(:value, :ends_at)
  end
end

app/controllers/bids_controller.rb
require "place_bid"

class BidsController < ApplicationController

  def create
    service = PlaceBid.new bid_params
    # if the service executes successfully, redirect to product page
    # passing in product_id params, that way we don't need to go to db and fetch another product
    if service.execute
      redirect_to product_path(params[:product_id]), notice: "Your bid went through."
    else
      redirect_to product_path(params[:product_id]), alert: "Your bid was not successful."
    end
  end

  private

  def bid_params
    # requiring the bid object and only permitting the value
    # merge additional data user id, auction id (params in URL)
    params.require(:bid).permit(:value).merge!(
      user_id: current_user.id,
      auction_id: params[:auction_id]
    )
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @products = Product.all
  end

  def show
  end

  def new
    @product = Product.new
    respond_with(@product)
  end

  def edit
  end

  def create
    @product = Product.new(product_params.merge! user_id: current_user.id)
    @product.save
    respond_with(@product)
  end

  def update
    @product.update(product_params)
    respond_with(@product)
  end

  def destroy
    @product.destroy
    respond_with(@product)
  end

  def transfer
    # only id in params because only have id in the route
    product = Product.find params[:id]

    # only transfer if the auction ended.
    if product.auction.ended?
      product.update_attribute :user_id, product.auction.top_bid.user_id
      # product is the same as product_path
      redirect_to product, notice: "Successfully transferred the product."
    else
      redirect_to product, alert: "The auction hasn't ended yet."
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/application/_nav.html.haml
/ add navi bar
%nav.navbar.navbar-default{role: "navigation"}
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", type: "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      =link_to "Awktion", root_path, class: "navbar-brand"
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li
          =link_to "Products", products_path

      %ul.nav.navbar-nav.navbar-right
        -if current_user
          %p.navbar-text
            You are signed in as #{current_user.email}.
            =link_to "Sign out", destroy_user_session_path, method: :delete
        -else
          %li=link_to "Sign in", new_user_session_path

app/views/auctions/_status.html.haml
-if @product.auction.top_bid.user_id == current_user.id
  %p You won the auction!
  / only user that won the product can see claim
  / method with put request to be set
  %p
    =link_to "Claim this product", transfer_product_path(@product), class: "btn btn-primary", method: :put
-else
  %p You lost the auction.

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Awktion</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "nav" %>
  <div class="container">
    <%= content_tag :div, alert, class: "flash bg-danger" if alert %>
    <%= content_tag :div, notice, class: "flash bg-success" if notice %>
    <%= yield %>
  </div>  

</body>
</html>

app/views/products/_auction.html.haml
-unless @product.has_auction?
  %h2 Put this product to auction

  =form_for [ @product, Auction.new ] do |f|
    %p
      =f.text_field :value

    %p
      =f.datetime_select :ends_at
      =f.button

app/views/products/_bid.html.haml
-if @product.has_auction?
  -if @product.auction.ended?
    =render "auctions/status"

  -else
    / display if a user logs in and the user doesn't hold the product and if there is an existing auction
    =form_for [ @product, @product.auction, Bid.new ] do |f|
      / need to know top bid
      %p.message
        %strong
          -if @product.auction.top_bid.present?
            -if @product.auction.top_bid.user_id == current_user.id
              Current bid:
            -else
              You were outbidded:
          -else
            Current bid:

          / if outbidded, post the current bid
          =@product.auction.current_bid

      / stringftime short
      / localize or l for short - resorts to internationalization
      / takes a timestamp and format option
      %p
        Ends at: #{l(@product.auction.ends_at, format: :short)} 

      / mechanism for users to submit a new bid
      %p
        =f.text_field :value
        =f.button class: "btn btn-primary"

  :javascript
    // initiate websocket object
    // jQuery function wrapper that is run at the end of the page
    // once the entire page is loaded, it will create that socket object
    $(function() {
      var user_id = "#{current_user.id}";
      var auction_id = "#{@product.auction.id}";
      var form = $("#new_bid");

      var auctionSocket = new AuctionSocket(
        user_id,
        auction_id,
        form
      );
    });

app/views/products/_form.html.haml
= form_for @product do |f|
  - if @product.errors.any?
    #error_explanation
      %h2= "#{pluralize(@product.errors.count, "error")} prohibited this product from being saved:"
      %ul
        - @product.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :image
    = f.text_field :image
  .actions
    = f.submit 'Save'

app/views/products/edit.html.haml
%h1 Editing product

= render 'form'

= link_to 'Show', @product
\|
= link_to 'Back', products_path

app/views/products/index.html.haml
%h1 Listing products

.row
  %ul.list-unstyled
    - @products.each do |product|
      %li.col-md-3
        %h2= link_to product.name, product
        %p
          =link_to product do 
            =image_tag product.image, height: 200
        %p
          =link_to 'Edit', edit_product_path(product)

          =link_to 'Destroy', product, :method => :delete, :data => { :confirm => 'Are you sure?' }

.row
  %p
    =link_to 'New Product', new_product_path, class: "btn btn-primary"

app/views/products/new.html.haml
%h1 New product

= render 'form'

= link_to 'Back', products_path

app/views/products/show.html.haml
%h1= @product.name
%p
  = image_tag @product.image, width: '50%', height: '50%'

%p
  = link_to 'Edit', edit_product_path(@product)
  \|
  = link_to 'Back', products_path

/ form to create new auction
=render "auction"
=render "bid"

/ ws part of websocket interface
/ host is the test, dev, production
/ port is the port we are on
/ ws://localhost:3000
/ request this url in the auction_websocketsjs
:javascript
  App = {
    websocket_url: "ws://#{request.host}:#{request.port}/"
  };